### ISSUE TITLE
getting the below errors

### ISSUE THREAD

**Issue by Surajsharma07** [tanhongit/new-mvc-shop#24] opened 2023-11-11 08:05 UTC
Warning: mysqli_query() expects parameter 1 to be mysqli, null given in C:\xampp\htdocs\lib\counter.php on line 66

( ! ) Warning: mysqli_query() expects parameter 1 to be mysqli, null given in C:\xampp\htdocs\lib\statistics.php on line 12

**Comment by tanhongit** [comment] 2023-11-11 09:02
@Surajsharma07 I understand, I will check it, thank you!

**Comment by halfagascan** [comment] 2023-11-17 21:20
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"

`2023/11/17 15:15:08 [error] 403683#403683: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, null given in /var/www/html/new-mvc-shop/lib/counter.php:66
Stack trace:
#0 /var/www/html/new-mvc-shop/lib/counter.php(66): mysqli_query()
#1 /var/www/html/new-mvc-shop/index.php(14): require('...')
#2 {main}
  thrown in /var/www/html/new-mvc-shop/lib/counter.php on line 66" while reading response header from upstream, client: 127.0.0.1, server: new-mvc-shop, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "localhost"`

Also can you explain more in detail regarding `5.2 Edit .htaccess` pretty new at this, so I'm unsure what and where to edit.
Thanks

**Comment by tanhongit** [comment] 2024-01-02 04:02
> Warning: mysqli_query() expects parameter 1 to be mysqli, null given in C:\xampp\htdocs\lib\counter.php on line 66
> 
> ( ! ) Warning: mysqli_query() expects parameter 1 to be mysqli, null given in C:\xampp\htdocs\lib\statistics.php on line 12

Sorry for the delay, I have now fixed this error, It is affected by upgrading to new mysql versions today. 
Please use the latest code version from the master branch.
Thanks!

**Comment by tanhongit** [comment] 2024-01-02 04:07
> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)" NAME="Debian GNU/Linux" VERSION_ID="12" VERSION="12 (bookworm)"
> 
> `2023/11/17 15:15:08 [error] 403683#403683: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, null given in /var/www/html/new-mvc-shop/lib/counter.php:66 Stack trace: #0 /var/www/html/new-mvc-shop/lib/counter.php(66): mysqli_query() #1 /var/www/html/new-mvc-shop/index.php(14): require('...') #2 {main} thrown in /var/www/html/new-mvc-shop/lib/counter.php on line 66" while reading response header from upstream, client: 127.0.0.1, server: new-mvc-shop, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "localhost"`
> 
> Also can you explain more in detail regarding `5.2 Edit .htaccess` pretty new at this, so I'm unsure what and where to edit. Thanks

The purpose of changing the rewrite base is to use it for subfolders. For example, if the user does not want the source to run on a new domain but only in a specific path of an existing domain (EX: abc.com/shop/), then they only need to edit /shop in htaccess.

I hope this answer can answer your questions.

**Comment by tanhongit** [comment] 2024-01-03 02:31
This issue will be closed because it has been confirmed to work well from other users. 
Thanks!

**Closed by tanhongit** 2024-01-03 02:31 UTC
